"""empty message

Revision ID: 5e3f0461421d
Revises: 17a958ea01c0
Create Date: 2020-05-12 11:40:41.855308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3f0461421d'
down_revision = '17a958ea01c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'seeking_description')
    # ### end Alembic commands ###
